name: CD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Bundle distributable artifact
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/bundle.sh

      - name: "Deploy to Azure"
        uses: azure/webapps-deploy@v3
        with:
          app-name: agileffp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist.zip
          # Add app settings using JSON format
          app-settings-json: |
            [
              {
                "name": "MICROSOFT_CLIENT_ID",
                "value": "${{ secrets.MICROSOFT_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "MICROSOFT_CLIENT_SECRET",
                "value": "${{ secrets.MICROSOFT_CLIENT_SECRET }}",
                "slotSetting": false
              }
            ]
        continue-on-error: true

      - name: Display deployment logs
        if: failure()
        run: |
          cat /tmp/zipdeploy/extracted/* # Adjust path as needed to display logs
